### ISSUE TITLE
Notify users of Google Analytics TOS

### ISSUE THREAD

**Issue by WilliamFeely** [dotnet/windows-sdk-for-google-analytics#11]
You should notify developers they should comply with the Google Analytics Terms of Service, which is available at https://www.google.com/analytics/terms/
In particular, section 7 requires that there be a Privacy Policy which discloses the use of Google Analytics and how it collects data.  A preferred method is by linking to https://www.google.com/policies/privacy/partners/ which is “How Google uses data when you use our partners' sites or apps”

**Comment by jaimerodriguez** [comment]
hi @WilliamFeely -- thanks for the tip.  I added a link to the terms of use from the FAQ and the Home documentation. I did not explicitly add the 'preferred method' because it is best they read it from Google's terms  of use.  Let me know if you feel that we need more.

**Comment by LindaLawton** [comment]
Hmm.   (thinking outloud)   users sign a ToS when they create their Google Analytics accounts.   I am not sure it matters which method they use for inserting the data.   (web,ios,android, windows sdk) .   Also the fact that they need to offer an opt out is part of the main created your account ToS.    

I am digging around the Documentation for Android and IOS see what they have in their.
