### ISSUE TITLE
Followup to #12

### ISSUE THREAD

**Issue by rogersachan** [dotnet/windows-sdk-for-google-analytics#13]
I cannot post a reply to my previous issue so I will make a new one here

I have recorded the issue here https://www.youtube.com/watch?v=ff-uJruE4CI&feature=youtu.be

I imagine this is an issue with security and permission on this repo, I can not create a PR so I worry that the bug will cripple this project.

**Comment by jaimerodriguez** [comment]
Hi @rogersachan -- we are contacting github support...   will update you soon.  If you need to create a  PR already let us know and we can find other ways. So far other folks have been able to submit PRs, so we are hoping it is not a broad issue.

**Comment by rogersachan** [comment]
I cannot star/PR from any other accounts (yet all other repos are fully functional)






On Mon, Feb 13, 2017 at 2:16 AM -0500, "Jaime Rodriguez" <notifications@github.com> wrote:












Hi @rogersachan -- we are contacting github support...   will update you soon.  If you need to create a  PR already let us know and we can find other ways. So far other folks have been able to submit PRs, so we are hoping it is not a broad issue.

**Comment by jongalloway** [comment]
@rogersachan - I contacted GitHub Support, they said that you will need to contact them directly. Just go to https://github.com/contact and file a support request referencing this Issue.
