### ISSUE TITLE
Can i use in Xamarin.Forms?

### ISSUE THREAD

**Issue by fumiya-kume** [dotnet/windows-sdk-for-google-analytics#14]

**Comment by LindaLawton** [comment]
I suspect that question is out of scope for this repo.  You may want to try http://stackoverflow.com/

**Comment by fumiya-kume** [comment]
sorry

**Comment by EmilAlipiev** [comment]
why is it out of scope? it is a very basic question as Xamarin belongs to Microsoft? Are you not dotnet and microsoft? why should we ask a question to other users instead of creators?

if you arent accepting any questions please change your documentation with comments below

> 
> Feedback and Requests
> Please use the issues page to submit any bugs, comments or questions, and feature requests.

**Comment by LindaLawton** [comment]
@EmilAlipiev  to my knowlage Xamarin is not supported
